### ISSUE TITLE
How do you add custom generators for the external option?

### ISSUE THREAD

**Issue by morganney** [json-schema-faker/grunt-jsonschema-faker#21]
The [docs](https://www.npmjs.com/package/grunt-jsonschema-faker#external-source-parameters) say "currently two generators are provided but you may write your own". How without modifying source code? I was unable to find an example.

Seems `generator` can be updated to support `string` (for default options of `random|cycle`) and `function` (for custom generators).

**Comment by morganney** [comment]
If the changes from #22 are published to npm this issue can be closed.

**Comment by ducin** [comment]
v0.3.2 published. Thanks @morganney for your contribution!
